using System.Diagnostics;
using System.Security.Cryptography;
using System.Buffers.Binary;
using ModForge;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Binary.Parameters;
using Mutagen.Bethesda.Plugins.Binary.Headers;
using Mutagen.Bethesda.Plugins.Masters;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using SkyrimRecordTypes = Mutagen.Bethesda.Skyrim.Internals.RecordTypes;
using Xunit;

namespace ModForge.Tests;

public sealed class CheckDependenciesTests
{
    [Fact]
    public void Parser_HandlesBomCommentsCaseAndExplicitImplicitList()
    {
        var plugins = PluginListing.Parse(new[]
        {
            "\uFEFF# generated by MO2", "*Update.esm", "Dawnguard.esm", "*MY MOD.esp", "",
        }, starred: true);
        var implicitPlugins = PluginListing.Parse(new[] { "Skyrim.esm", "ccBGSSSE001-Fish.esm" }, starred: false);

        var result = InstalledDependencies.Check(
            new[] { "skyrim.ESM", "update.ESM", "Dawnguard.esm", "Missing.esl" },
            plugins, implicitPlugins);

        Assert.Equal(new[]
        {
            InstalledDependencyState.Implicit,
            InstalledDependencyState.Enabled,
            InstalledDependencyState.Disabled,
            InstalledDependencyState.Missing,
        }, result.Dependencies.Select(x => x.State));
        Assert.False(result.Satisfied);
    }

    [Fact]
    public void Parser_RejectsConflictingDuplicate()
    {
        var error = Assert.Throws<InvalidDataException>(() =>
            PluginListing.Parse(new[] { "*Same.esp", "same.ESP" }, starred: true));
        Assert.Contains("both enabled and disabled", error.Message);
    }

    [Theory]
    [InlineData("folder\\Bad.esp")]
    [InlineData("folder/Bad.esp")]
    [InlineData("Bad:Name.esp")]
    [InlineData(".esp")]
    [InlineData("not-a-plugin.txt")]
    public void Parser_RejectsInvalidPluginNamesOnEveryPlatform(string name)
    {
        Assert.Throws<InvalidDataException>(() => PluginListing.Parse(new[] { "*" + name }, starred: true));
    }

    [Fact]
    public void EmptyAndAllDisabledLists_DoNotBecomeAllActive()
    {
        var empty = PluginListing.Parse(Array.Empty<string>(), starred: true);
        var disabled = PluginListing.Parse(new[] { "Skyrim.esm" }, starred: true);

        Assert.Equal(InstalledDependencyState.Missing,
            Assert.Single(InstalledDependencies.Check(new[] { "Skyrim.esm" }, empty).Dependencies).State);
        Assert.Equal(InstalledDependencyState.Disabled,
            Assert.Single(InstalledDependencies.Check(new[] { "Skyrim.esm" }, disabled).Dependencies).State);
    }

    [Fact]
    public void ReadDirectMasters_ReadsHeaderWithoutRecords()
    {
        var dir = NewTempDir();
        try
        {
            var plugin = WritePlugin(dir, "Input.esp", "Skyrim.esm", "Required.esp");
            Assert.Equal(new[] { "Skyrim.esm", "Required.esp" }, InstalledDependencies.ReadDirectMasters(plugin));
        }
        finally { Directory.Delete(dir, recursive: true); }
    }

    [Fact]
    public void CliRealProcess_ReturnsZeroOneTwo_AndDoesNotChangeInputs()
    {
        var dir = NewTempDir();
        try
        {
            var plugin = WritePlugin(dir, "Input.esp", "Skyrim.esm", "Required.esp");
            var plugins = Path.Combine(dir, "plugins.txt");
            var implicitPlugins = Path.Combine(dir, "implicit.txt");
            File.WriteAllText(plugins, "*Required.esp\n");
            File.WriteAllText(implicitPlugins, "Skyrim.esm\n");
            var before = new[] { plugin, plugins, implicitPlugins }.ToDictionary(x => x, Sha256);

            var ok = RunCli("check-dependencies", plugin, "--plugins", plugins,
                "--implicit-plugins", implicitPlugins);
            Assert.Equal(0, ok.ExitCode);
            Assert.Contains("enabled: Required.esp", ok.Stdout);
            Assert.Contains("enabled (implicit list): Skyrim.esm", ok.Stdout);

            File.WriteAllText(plugins, "Required.esp\n");
            var missing = RunCli("check-dependencies", plugin, "--plugins", plugins,
                "--implicit-plugins", implicitPlugins);
            Assert.Equal(1, missing.ExitCode);
            Assert.Contains("DISABLED: Required.esp", missing.Stderr);

            var badArgs = RunCli("check-dependencies", plugin);
            Assert.Equal(2, badArgs.ExitCode);
            Assert.Contains("usage: check-dependencies", badArgs.Stderr);

            Assert.Equal(before[plugin], Sha256(plugin));
            Assert.Equal(before[implicitPlugins], Sha256(implicitPlugins));
        }
        finally { Directory.Delete(dir, recursive: true); }
    }

    [Fact]
    public void InvalidListingAndTruncatedPluginFailClosed()
    {
        var dir = NewTempDir();
        try
        {
            var badList = Path.Combine(dir, "plugins.txt");
            File.WriteAllText(badList, "*not-a-plugin.txt\n");
            Assert.Throws<InvalidDataException>(() => PluginListing.ReadPluginsFile(badList));

            var truncated = Path.Combine(dir, "broken.esp");
            File.WriteAllBytes(truncated, new byte[] { 0x54, 0x45, 0x53, 0x34 });
            Assert.ThrowsAny<Exception>(() => InstalledDependencies.ReadDirectMasters(truncated));

            var valid = WritePlugin(dir, "valid.esp", "Skyrim.esm");
            var bytes = File.ReadAllBytes(valid);
            File.WriteAllBytes(truncated, bytes[..^5]);
            Assert.ThrowsAny<Exception>(() => InstalledDependencies.ReadDirectMasters(truncated));

            bytes[0] = (byte)'B';
            File.WriteAllBytes(truncated, bytes);
            Assert.ThrowsAny<Exception>(() => InstalledDependencies.ReadDirectMasters(truncated));

            bytes = File.ReadAllBytes(valid);
            var modPath = new ModPath(valid);
            var header = ModHeaderFrame.FromPath(modPath, GameRelease.SkyrimSE);
            var data = header.EnumerateSubrecords().Single(x => x.RecordType == SkyrimRecordTypes.DATA);
            var withoutData = bytes[..data.Location].Concat(bytes[data.EndLocation..]).ToArray();
            BinaryPrimitives.WriteUInt32LittleEndian(withoutData.AsSpan(4, 4),
                header.ContentLength - (uint)data.TotalLength);
            File.WriteAllBytes(truncated, withoutData);
            Assert.Throws<InvalidDataException>(() => InstalledDependencies.ReadDirectMasters(truncated));

            var emptyHeader = bytes[..header.HeaderLength];
            BinaryPrimitives.WriteUInt32LittleEndian(emptyHeader.AsSpan(4, 4), 0);
            File.WriteAllBytes(truncated, emptyHeader);
            Assert.Throws<InvalidDataException>(() => InstalledDependencies.ReadDirectMasters(truncated));
        }
        finally { Directory.Delete(dir, recursive: true); }
    }

    private static string WritePlugin(string dir, string name, params string[] masters)
    {
        var path = Path.Combine(dir, name);
        var mod = new SkyrimMod(ModKey.FromNameAndExtension(name), SkyrimRelease.SkyrimSE);
        foreach (var master in masters)
            mod.ModHeader.MasterReferences.Add(new MasterReference
                { Master = ModKey.FromNameAndExtension(master), FileSize = 0 });
        mod.WriteToBinary(path, new BinaryWriteParameters
        {
            ModKey = ModKeyOption.NoCheck,
            MastersListContent = MastersListContentOption.NoCheck,
        });
        return path;
    }

    private static (int ExitCode, string Stdout, string Stderr) RunCli(params string[] args)
    {
        var cli = typeof(Program).Assembly.Location;
        var host = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "dotnet", "dotnet.exe");
        if (!File.Exists(host)) host = "dotnet";
        var start = new ProcessStartInfo(host)
        {
            UseShellExecute = false, RedirectStandardOutput = true, RedirectStandardError = true,
        };
        start.ArgumentList.Add(cli);
        foreach (var arg in args) start.ArgumentList.Add(arg);
        using var process = Process.Start(start) ?? throw new InvalidOperationException("could not start CLI");
        var stdout = process.StandardOutput.ReadToEnd();
        var stderr = process.StandardError.ReadToEnd();
        process.WaitForExit();
        return (process.ExitCode, stdout, stderr);
    }

    private static string NewTempDir()
    {
        var path = Path.Combine(Path.GetTempPath(), "mf-dependencies-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(path);
        return path;
    }

    private static string Sha256(string path) => Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path)));
}
