set(headers ${headers}
    src/PCH.h
    src/log.h
    src/Aim.h
    src/Editor.h
    src/Eraser.h
    src/Markers.h
    src/Overrides.h
    src/Captures.h
    src/Palette.h
    src/Physics.h
    src/Referrer.h
    src/Requires.h
    src/SceneExporter.h
    src/UI.h
    src/Modes.h
    src/KeyIni.h
    src/Console.h
    src/CoSave.h
)
