set(sources ${sources}
    src/plugin.cpp
    src/Aim.cpp
    src/Captures.cpp
    src/Editor.cpp
    src/Eraser.cpp
    src/Markers.cpp
    src/Overrides.cpp
    src/Palette.cpp
    src/Palette.Placed.cpp
    src/Physics.cpp
    src/Referrer.cpp
    src/Requires.cpp
    src/SceneExporter.cpp
    src/UI.cpp
    src/UI.Markers.cpp
    src/UI.References.cpp
    src/UI.Settings.cpp
    src/Modes.cpp
    src/Console.cpp
    src/CoSave.cpp
)
