namespace ModForge;

public static partial class Generator
{
    /// <summary>Property name on a generated TIF script that holds the owning quest reference.</summary>
    internal const string TifQuestPropertyName = "OwningQuest";

    /// <summary>Scriptname of the reusable presence-gated Scene controller (extends Quest), attached to a
    /// host quest when a scene declares autoStart. One prebuilt .pex (embedded in the CLI) serves every
    /// generated mod; Package ships it whenever a scene uses autoStart.</summary>
    internal const string SceneBanterController = "MFSceneBanterController";

    /// <summary>Scriptname of the reusable SM-encounter anti-spam cooldown (extends Quest). Attached to a
    /// storyEvent quest declaring `cooldownHours`; one prebuilt .pex serves every generated mod.</summary>
    internal const string EncounterCooldownScript = "MFEncounterCooldown";

    /// <summary>Scriptname of the reusable dynamic near-player spawn (extends Quest). Attached to a quest
    /// declaring `spawn`; one prebuilt .pex serves every generated mod.</summary>
    internal const string DynamicSpawnScript = "MFDynamicSpawn";

    /// <summary>Scriptname of the reusable primary-identity controller (extends Quest). Maintains the
    /// MF_PrimaryIdentity global; one prebuilt .pex (embedded in the CLI) serves every generated mod.</summary>
    internal const string IdentityController = "MFIdentityController";

    /// <summary>The auto-built global holding the player's CURRENT primary identity code (0 = none). Read
    /// by primaryIdentity greeting CTDA; written by the controller.</summary>
    internal const string IdentityPrimaryGlobal = "MF_PrimaryIdentity";

    /// <summary>The auto-built global holding the player's MANUAL override code (0 = auto). Written by a
    /// dialogue option (setPrimaryIdentity); read by the controller.</summary>
    internal const string IdentityOverrideGlobal = "MF_IdentityOverride";

    /// <summary>The stable per-identity numeric code used by the controller / greeting CTDA / override
    /// fragment: 1-based index into spec.Identities. 0 for "auto"/empty (no/clear override); -1 if unknown.</summary>
    public static int IdentityCode(ModSpec spec, string id)
    {
        if (string.IsNullOrWhiteSpace(id) || string.Equals(id, "auto", StringComparison.OrdinalIgnoreCase)) return 0;
        for (int i = 0; i < spec.Identities.Count; i++)
            if (string.Equals(spec.Identities[i].Id, id, StringComparison.OrdinalIgnoreCase)) return i + 1;
        return -1;
    }

    /// <summary>The Papyrus source for a dialogue line that advances a stage and/or sets the primary-identity
    /// override when picked (the TIF dialogue-fragment equivalent). SetStage uses an explicit Quest property
    /// rather than GetOwningQuest() — GetOwningQuest() can return None at runtime for StartGameEnabled quests,
    /// silently skipping SetStage. Properties are bound in the INFO VMAD by <c>package</c>. <paramref
    /// name="overrideCode"/> ≥ 0 emits the override SetValue (0 = clear/auto); -1 = no override line.</summary>
    /// <summary>Property name on a generated TIF script that holds the reward item/gold form.</summary>
    internal const string TifRewardPropertyName = "RewardItem";
    /// <summary>Property name on a generated TIF script that holds the mutable reputation/counter global.</summary>
    internal const string TifSetGlobalPropertyName = "TargetGlobal";

    public static string GenerateDialogueFragmentSource(DialogueSpec d, int overrideCode = -1)
    {
        bool setsStage = d.SetStage >= 0;
        bool setsOverride = overrideCode >= 0;
        bool opensBarter = d.OpenBarter;
        bool setsGlobal = d.SetGlobal is { } sg && !string.IsNullOrWhiteSpace(sg.Global) && (sg.Value.HasValue || sg.Delta.HasValue);
        bool rewards = !string.IsNullOrWhiteSpace(d.RewardItem);
        bool reevals = d.EvaluateSpeakerPackages;
        bool persists = HasPersist(d);
        bool syncs = HasSyncPerks(d);
        bool storages = HasStorageWrites(d);
        if (!setsStage && !setsOverride && !opensBarter && !setsGlobal && !rewards && !reevals && !persists && !syncs && !storages) return "";
        var name = DialogueFragmentScriptName(d);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends TopicInfo Hidden");
        sb.AppendLine("; AUTO-GENERATED by ModForge — dialogue line result (setStage / identity override / global / barter / reward / re-eval).");
        sb.AppendLine("; Object properties are bound to their FormKeys in the ESP VMAD by `package`.");
        sb.AppendLine();
        if (setsStage) sb.AppendLine($"Quest Property {TifQuestPropertyName} Auto");
        if (setsOverride) sb.AppendLine($"GlobalVariable Property {IdentityOverrideGlobal} Auto");
        if (setsGlobal) sb.AppendLine($"GlobalVariable Property {TifSetGlobalPropertyName} Auto");
        if (rewards) sb.AppendLine($"Form Property {TifRewardPropertyName} Auto");
        foreach (var decl in JContainersPropertyDecls(d)) sb.AppendLine(decl);
        // J組 storageWrites arbitrary-ref targets bind a Form property each (speaker/player/none declare nothing).
        foreach (var decl in StorageWritesPropertyDecls("", d.StorageWrites)) sb.AppendLine(decl);
        sb.AppendLine();
        sb.AppendLine("Function Fragment_0(ObjectReference akSpeakerRef)");
        if (setsStage) sb.AppendLine($"    {TifQuestPropertyName}.SetStage({d.SetStage})");
        if (setsOverride) sb.AppendLine($"    {IdentityOverrideGlobal}.SetValue({overrideCode})");
        if (setsGlobal)
        {
            if (d.SetGlobal!.Value.HasValue)
                sb.AppendLine($"    {TifSetGlobalPropertyName}.SetValue({PapyrusFloat(d.SetGlobal.Value.Value)})");
            if (d.SetGlobal.Delta.HasValue)
                sb.AppendLine($"    {TifSetGlobalPropertyName}.Mod({PapyrusFloat(d.SetGlobal.Delta.Value)})");
        }
        if (rewards) sb.AppendLine($"    Game.GetPlayer().AddItem({TifRewardPropertyName}, {(d.RewardCount < 1 ? 1 : d.RewardCount)})");
        if (opensBarter || reevals)
        {
            sb.AppendLine("    Actor __spk = akSpeakerRef as Actor");
            sb.AppendLine("    If __spk");
            // Vanilla natives — ShowBarterMenu() opens trade with a vendor speaker; EvaluatePackage()
            // re-runs the speaker's AI packages so a stage-gated follow/escort package activates now.
            if (opensBarter) sb.AppendLine("        __spk.ShowBarterMenu()");
            if (reevals)     sb.AppendLine("        __spk.EvaluatePackage()");
            sb.AppendLine("    EndIf");
        }
        // JContainers JFormDB writes, then perk sync (both keyed on speaker/player). Emitted last so a
        // perk sync sees the ranks this line just persisted.
        foreach (var line in JContainersFragmentBody(d)) sb.AppendLine("    " + line);
        // J組 PapyrusUtil StorageUtil per-Form KV writes (speaker/player/none = pure expressions; an
        // arbitrary-ref target reads the bound SWRef_<i> Form property; fromJson sources the value via JsonUtil).
        foreach (var line in StorageWritesBody(d.StorageWrites, "")) sb.AppendLine("    " + line);
        sb.AppendLine("EndFunction");
        return sb.ToString();
    }

    public static string DialogueFragmentScriptName(DialogueSpec d) =>
        (d.SetStage >= 0 || !string.IsNullOrWhiteSpace(d.SetPrimaryIdentity) || d.OpenBarter
         || (d.SetGlobal is { } sg && !string.IsNullOrWhiteSpace(sg.Global)) || !string.IsNullOrWhiteSpace(d.RewardItem)
         || d.EvaluateSpeakerPackages || HasPersist(d) || HasSyncPerks(d) || HasStorageWrites(d)) ? $"TIF_{Sanitize(d.EditorId)}" : "";

}
