internal static partial class Program
{
    // -------------------------------------------------------------------------------
    //  package step 1 — pre-compile the .psc files ModForge GENERATES from the spec
    //  (quest-stage / dialogue set-stage / scene / perk / MCM fragments). Split out of
    //  Package.cs (2026-08-27). Must run before Generator.Build so the VMAD can be
    //  attached only for fragments whose .pex is confirmed present.
    // -------------------------------------------------------------------------------
    // Returns false when a REQUIRED fragment failed to compile (caller aborts the package).
    // autoCompiled receives the number of generated fragments that did compile.
    private static bool PrecompileGeneratedFragments(ModSpec spec, string compiledFragmentsDir,
                                                     string sourceDir, out int autoCompiled)
    {
        var n = 0;
        // Run the pass-0 macro-expansions NOW (idempotent — Build() re-runs them as a no-op) so that
        // fragments generated BY a macro — e.g. an npcRoles blacksmith's openBarter trade topic, or a
        // livingNpcs interaction's setGlobal — exist in spec.Dialogue/Quests before the compile loops
        // below. Without this, macro-generated fragments never compile and their VMAD is silently dropped.
        Generator.ExpandMacros(spec);

        bool CompileGenerated(string pscSource, string scriptName, string label)
        {
            if (CompileGeneratedFragment(pscSource, scriptName, label, compiledFragmentsDir, sourceDir))
            {
                n++;
                return true;
            }
            return false;
        }

        // A <quest>_Stages fragment that drives a dynamic spawn / cooldown casts `self as MFDynamicSpawn`
        // / `self as MFEncounterCooldown` — from the startUpStage fragment (StartGameEnabled spawn) OR the
        // OnStory<Event> handler (Story-Manager encounter, see Generator.StoryTrigger). The Papyrus
        // compiler resolves those types from the input file's own directory, so drop their embedded SOURCE
        // beside the fragment .psc here in EITHER case.
        if (spec.Quests.Any(q => Generator.StartupStageTrigger(q) is not null || Generator.StoryTrigger(q)))
            foreach (var psc in new[] { "MFDynamicSpawn.psc", "MFEncounterCooldown.psc" })
            {
                using var rs = typeof(Program).Assembly.GetManifestResourceStream(psc);
                if (rs is null) continue;
                using var fs = File.Create(Path.Combine(compiledFragmentsDir, psc));
                rs.CopyTo(fs);
            }

        foreach (var q in spec.Quests)
        {
            var src = Generator.GenerateQuestFragmentSource(q);
            if (!string.IsNullOrEmpty(src))
                CompileGenerated(src, Generator.QuestFragmentScriptName(q), $"quest fragment for '{q.EditorId}'");
        }
        foreach (var d in spec.Dialogue)
        {
            // setPrimaryIdentity → the override code baked into the fragment (0 = clear/auto).
            var overrideCode = string.IsNullOrWhiteSpace(d.SetPrimaryIdentity) ? -1 : Generator.IdentityCode(spec, d.SetPrimaryIdentity);
            var src = Generator.GenerateDialogueFragmentSource(d, overrideCode);
            if (!string.IsNullOrEmpty(src))
                CompileGenerated(src, Generator.DialogueFragmentScriptName(d), $"dialogue fragment for '{d.EditorId}'");
        }
        bool requiredSceneFragmentsReady = CompileRequiredSceneFragments(spec, CompileGenerated);
        foreach (var pk in spec.Perks)
        {
            var src = Generator.GeneratePerkFragmentSource(pk);
            if (!string.IsNullOrEmpty(src))
                CompileGenerated(src, Generator.PerkFragmentScriptName(pk), $"perk fragment for '{pk.EditorId}'");
        }

        // Short-circuit preserved: when the scene fragments already failed, the MCM bridges are
        // NOT compiled — same as the original `!ready || !CompileRequiredMcmBridges(...)`.
        var ok = requiredSceneFragmentsReady && CompileRequiredMcmBridges(spec, CompileGenerated);
        // Assigned AFTER the call above: CompileRequiredMcmBridges also goes through
        // CompileGenerated, so its increments must be included in the count.
        autoCompiled = n;
        return ok;
    }
}