namespace ModForge;

public static partial class Generator
{
    // -------------------------------------------------------------------------------
    //  Scene phase-fragment GENERATION (PlayIdle) — the THIRD fragment family.
    //
    //  SceneAction.TypeEnum has no native "play animation" beat (only Dialog/Package/Timer).
    //  Skyrim's standard way to animate a scene actor is a SCEN SceneAdapter whose per-phase
    //  begin fragment calls `<alias>.GetActorRef().PlayIdle(<idle>)`. An "idle action"
    //  (SceneActionSpec.Idle non-empty) compiles to exactly that.
    //
    //  Decoded (Task 0 spike, 2026-06-07) from vanilla SF_BardSongsBallad01Scene /
    //  SF_MQ201EscapeScene: the SF_ script `extends Scene`, declares a `ReferenceAlias` property
    //  per actor (bound by `package` to the host-quest alias) and an `Idle` property per idle,
    //  and fires `<Alias>.GetActorRef().PlayIdle(<Idle>)`. The vanilla method is GetActorRef()
    //  (NOT GetActorReference — that does not exist on ReferenceAlias).
    //
    //  Like GenerateQuestFragmentSource this is a pure function (string in / string out),
    //  unit-testable with no Skyrim master / Wine dependency. The matching VMAD + property
    //  binding lives in Generator.Build.Scripts.AttachSceneFragments (driven by `package`).
    // -------------------------------------------------------------------------------

    /// <summary>True when a scene has at least one idle action (needs an SF_ phase-fragment script).</summary>
    public static bool SceneNeedsFragmentScript(SceneSpec s) =>
        s.Actions.Any(a => !string.IsNullOrWhiteSpace(a.Idle));

    /// <summary>The Papyrus script Name for a scene's phase-fragment script, or empty if none needed.</summary>
    public static string SceneFragmentScriptName(SceneSpec s) =>
        SceneNeedsFragmentScript(s) ? $"SF_{Sanitize(s.EditorId)}" : "";

    /// <summary>The idle actions that drive fragments: one per phase (first wins if several share a
    /// phase), ascending by phase. The phase index doubles as the fragment counter (Fragment_&lt;phase&gt;)
    /// — collision-free because there is at most one idle per phase.</summary>
    internal static IEnumerable<SceneActionSpec> SceneIdleActions(SceneSpec s) =>
        s.Actions
            .Where(a => !string.IsNullOrWhiteSpace(a.Idle))
            .GroupBy(a => a.StartPhase)
            .Select(g => g.First())
            .OrderBy(a => a.StartPhase);

    /// <summary>Papyrus source for a scene's phase-fragment script: one Fragment per phase that has an
    /// idle action, each playing that action's idle on the action's actor. The idle form and the actor
    /// alias are bound as script properties by `package` (AttachSceneFragments).</summary>
    public static string GenerateSceneFragmentSource(SceneSpec s)
    {
        if (!SceneNeedsFragmentScript(s)) return "";
        var name = SceneFragmentScriptName(s);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends Scene Hidden");
        sb.AppendLine("; AUTO-GENERATED by ModForge — scene phase idle playback.");
        sb.AppendLine("; `package` compiles this and attaches the SceneAdapter VMAD + properties automatically.");
        sb.AppendLine();

        foreach (var a in SceneIdleActions(s))
        {
            // Properties bound by package: Idle_<phase> (the IDLE) and Actor_<phase> (host-quest alias).
            sb.AppendLine($"Idle Property Idle_{a.StartPhase} Auto");
            sb.AppendLine($"ReferenceAlias Property Actor_{a.StartPhase} Auto");
            sb.AppendLine($"Function Fragment_{a.StartPhase}()");
            sb.AppendLine($"    ; phase {a.StartPhase}: alias {a.Actor} plays idle {OneLine(a.Idle)}");
            sb.AppendLine($"    Actor a = Actor_{a.StartPhase}.GetActorRef()");
            sb.AppendLine("    if a");
            sb.AppendLine($"        a.PlayIdle(Idle_{a.StartPhase})");
            sb.AppendLine("    endif");
            sb.AppendLine("EndFunction");
            sb.AppendLine();
        }
        return sb.ToString();
    }
}
