namespace ModForge;

public static partial class Generator
{
    // Vanilla-canonical PerkConditionTabCount per entry-point type (extracted from Skyrim.esm's 375
    // PERK records). This byte is the entry point's intrinsic number of condition tabs (e.g. attacker /
    // target / weapon contexts) — the game uses it to size the per-tab condition array, so it must be
    // non-zero and match vanilla even when we author conditions on tab 0 only. Unlisted entry points
    // fall back to 2 (a safe non-zero default >= the single tab-0 group we ever emit).
    private static readonly Dictionary<APerkEntryPointEffect.EntryType, byte> EntryPointTabCount = new()
    {
        [APerkEntryPointEffect.EntryType.Activate] = 2,
        [APerkEntryPointEffect.EntryType.ApplyBashingSpell] = 2,
        [APerkEntryPointEffect.EntryType.ApplyCombatHitSpell] = 3,
        [APerkEntryPointEffect.EntryType.ApplyReanimateSpell] = 3,
        [APerkEntryPointEffect.EntryType.ApplySneakingSpell] = 1,
        [APerkEntryPointEffect.EntryType.ApplyWeaponSwingSpell] = 3,
        [APerkEntryPointEffect.EntryType.CalculateMyCriticalHitChance] = 3,
        [APerkEntryPointEffect.EntryType.CalculateMyCriticalHitDamage] = 3,
        [APerkEntryPointEffect.EntryType.CalculateWeaponDamage] = 3,
        [APerkEntryPointEffect.EntryType.CanDualCastSpell] = 2,
        [APerkEntryPointEffect.EntryType.CanPickpocketEquippedItem] = 3,
        [APerkEntryPointEffect.EntryType.FilterActivation] = 2,
        [APerkEntryPointEffect.EntryType.MakeLockpicksUnbreakable] = 1,
        [APerkEntryPointEffect.EntryType.ModAlchemyEffectiveness] = 1,
        [APerkEntryPointEffect.EntryType.ModArmorRating] = 2,
        [APerkEntryPointEffect.EntryType.ModArmorWeight] = 2,
        [APerkEntryPointEffect.EntryType.ModAttackDamage] = 3,
        [APerkEntryPointEffect.EntryType.ModBashingDamage] = 2,
        [APerkEntryPointEffect.EntryType.ModBowZoom] = 2,
        [APerkEntryPointEffect.EntryType.ModBuyPrices] = 2,
        [APerkEntryPointEffect.EntryType.ModCommandedActorLimit] = 2,
        [APerkEntryPointEffect.EntryType.ModDetectionLight] = 2,
        [APerkEntryPointEffect.EntryType.ModDetectionSneakSkill] = 2,
        [APerkEntryPointEffect.EntryType.ModEnchantmentPower] = 3,
        [APerkEntryPointEffect.EntryType.ModFallingDamage] = 1,
        [APerkEntryPointEffect.EntryType.ModIncomingDamage] = 3,
        [APerkEntryPointEffect.EntryType.ModIncomingSpellMagnitude] = 2,
        [APerkEntryPointEffect.EntryType.ModIncomingStagger] = 2,
        [APerkEntryPointEffect.EntryType.ModIngredientsHarvested] = 2,
        [APerkEntryPointEffect.EntryType.ModInitialIngredientEffectsLearned] = 2,
        [APerkEntryPointEffect.EntryType.ModLockpickingCrimeChance] = 2,
        [APerkEntryPointEffect.EntryType.ModLockpickingKeyRewardChance] = 2,
        [APerkEntryPointEffect.EntryType.ModLockpickSweetSpot] = 2,
        [APerkEntryPointEffect.EntryType.ModNumAppliedEnchantmentsAllowed] = 1,
        [APerkEntryPointEffect.EntryType.ModPercentBlocked] = 1,
        [APerkEntryPointEffect.EntryType.ModPickpocketChance] = 3,
        [APerkEntryPointEffect.EntryType.ModPlayerIntimidation] = 2,
        [APerkEntryPointEffect.EntryType.ModPlayerMagicSlowdown] = 2,
        [APerkEntryPointEffect.EntryType.ModPoisonDoseCount] = 3,
        [APerkEntryPointEffect.EntryType.ModPotionsCreated] = 2,
        [APerkEntryPointEffect.EntryType.ModPowerAttackDamage] = 3,
        [APerkEntryPointEffect.EntryType.ModPowerAttackStamina] = 2,
        [APerkEntryPointEffect.EntryType.ModRecoverArrowChance] = 1,
        [APerkEntryPointEffect.EntryType.ModSellPrices] = 2,
        [APerkEntryPointEffect.EntryType.ModShieldDefectArrowChance] = 1,
        [APerkEntryPointEffect.EntryType.ModShoutOk] = 1,
        [APerkEntryPointEffect.EntryType.ModSkillUse] = 1,
        [APerkEntryPointEffect.EntryType.ModSneakAttackMult] = 3,
        [APerkEntryPointEffect.EntryType.ModSoulGemRecharge] = 2,
        [APerkEntryPointEffect.EntryType.ModSoulPercentCapturedToWeapon] = 3,
        [APerkEntryPointEffect.EntryType.ModSpellCastingSoundEvent] = 2,
        [APerkEntryPointEffect.EntryType.ModSpellCost] = 2,
        [APerkEntryPointEffect.EntryType.ModSpellDuration] = 3,
        [APerkEntryPointEffect.EntryType.ModSpellMagnitude] = 3,
        [APerkEntryPointEffect.EntryType.ModSpellRange] = 2,
        [APerkEntryPointEffect.EntryType.ModTargetDamageResistance] = 3,
        [APerkEntryPointEffect.EntryType.ModTargetStagger] = 2,
        [APerkEntryPointEffect.EntryType.ModTemperingHealth] = 2,
        [APerkEntryPointEffect.EntryType.ModWardMagickaAbsorptionPct] = 2,
        [APerkEntryPointEffect.EntryType.PurifyAlchemyIngredients] = 1,
        [APerkEntryPointEffect.EntryType.SetBooleanGraphVariable] = 1,
        [APerkEntryPointEffect.EntryType.SetLockpickStartingArc] = 1,
        [APerkEntryPointEffect.EntryType.SetSweepAttack] = 2,
        [APerkEntryPointEffect.EntryType.ShouldApplyPlacedItem] = 3,
    };
}
