namespace ModForge;

public static partial class Generator
{
    // -------------------------------------------------------------------------------
    //  Quest fragment-script GENERATION (It. quest-stages).
    //
    //  Stages + log entries are pure RECORD data (built in Generator.Build). But two pieces
    //  of "quest LOGIC" can only run via Papyrus in Skyrim:
    //    * displaying / completing an OBJECTIVE when a stage is reached
    //      (SetObjectiveDisplayed / SetObjectiveCompleted), and
    //    * advancing a STAGE when a dialogue line is picked (GetOwningQuest().SetStage()).
    //  Vanilla does both with CK-generated fragment scripts (QF_<quest>_<formid> stage
    //  fragments + TIF_<formid> dialogue fragments). We can't drive the Creation Kit
    //  headless, so we GENERATE the equivalent Papyrus SOURCE for the author to compile
    //  (the `package` command writes it under Scripts/Source/). The quest base script is
    //  attached to the QUST record via the normal VMAD script mechanism; the per-stage
    //  Fragment_N hooks must be bound in the CK (the one step we can't do on Linux).
    //
    //  This generator is a pure function (string in / string out) so it's unit-testable
    //  with no Skyrim master / Wine dependency.
    // -------------------------------------------------------------------------------

    /// <summary>The Papyrus script Name attached to a quest that has stage→objective wiring or
    /// dialogue-set-stage logic. Empty if the quest needs no fragment script.</summary>
    public static string QuestFragmentScriptName(QuestSpec q) =>
        QuestNeedsFragmentScript(q) ? $"{Sanitize(q.EditorId)}_Stages" : "";

    /// <summary>True when a quest has objectives linked to stages (showStage/completeStage).</summary>
    public static bool QuestNeedsFragmentScript(QuestSpec q) =>
        q.Objectives.Any(o => o.ShowStage >= 0 || o.CompleteStage >= 0);

    /// <summary>The Papyrus source for a quest's stage-fragment script. One Fragment per stage that
    /// displays/completes the objectives linked to it. Function names follow the CK convention
    /// (<c>Fragment_Stage_XXXX_Item00000</c>) so the engine calls them automatically when
    /// <c>SetStage()</c> fires — no CK binding step needed once the .pex is compiled and the
    /// VMAD is attached by <c>package</c>.</summary>
    public static string GenerateQuestFragmentSource(QuestSpec q)
    {
        if (!QuestNeedsFragmentScript(q)) return "";
        var name = QuestFragmentScriptName(q);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends Quest");
        sb.AppendLine("; AUTO-GENERATED by ModForge — quest stage → objective wiring.");
        sb.AppendLine("; `package` compiles this and attaches the QuestAdapter VMAD automatically;");
        sb.AppendLine("; no Creation Kit binding step is needed.");
        sb.AppendLine();

        // Stages that show or complete an objective, in ascending order.
        var stageNums = q.Objectives
            .SelectMany(o => new[] { o.ShowStage, o.CompleteStage })
            .Where(s => s >= 0).Distinct().OrderBy(s => s);

        foreach (var stage in stageNums)
        {
            // CK-standard name: engine calls Fragment_Stage_XXXX_Item00000 on the script when
            // SetStage(XXXX) fires (first log entry = Item00000). No manual binding required.
            sb.AppendLine($"Function Fragment_Stage_{stage:D4}_Item00000()");
            foreach (var o in q.Objectives.Where(o => o.ShowStage == stage))
                sb.AppendLine($"    SetObjectiveDisplayed({o.Index})   ; show: {OneLine(o.Text)}");
            foreach (var o in q.Objectives.Where(o => o.CompleteStage == stage))
                sb.AppendLine($"    SetObjectiveCompleted({o.Index})   ; complete: {OneLine(o.Text)}");
            sb.AppendLine("EndFunction");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    /// <summary>Property name on a generated TIF script that holds the owning quest reference.</summary>
    internal const string TifQuestPropertyName = "OwningQuest";

    /// <summary>The Papyrus source for a dialogue line that advances a stage when picked (the TIF
    /// dialogue-fragment equivalent). Uses an explicit Quest property rather than GetOwningQuest()
    /// — GetOwningQuest() can return None at runtime for StartGameEnabled quests, silently skipping
    /// SetStage. The property is bound to the quest FormKey in the INFO VMAD by <c>package</c>.</summary>
    public static string GenerateDialogueFragmentSource(DialogueSpec d)
    {
        if (d.SetStage < 0) return "";
        var name = DialogueFragmentScriptName(d);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends TopicInfo Hidden");
        sb.AppendLine("; AUTO-GENERATED by ModForge — dialogue line → SetStage.");
        sb.AppendLine("; OwningQuest property is bound to the quest FormKey in the ESP VMAD by `package`.");
        sb.AppendLine();
        sb.AppendLine($"Quest Property {TifQuestPropertyName} Auto");
        sb.AppendLine();
        sb.AppendLine("Function Fragment_0(ObjectReference akSpeakerRef)");
        sb.AppendLine($"    {TifQuestPropertyName}.SetStage({d.SetStage})");
        sb.AppendLine("EndFunction");
        return sb.ToString();
    }

    public static string DialogueFragmentScriptName(DialogueSpec d) =>
        d.SetStage >= 0 ? $"TIF_{Sanitize(d.EditorId)}" : "";

    private static string Sanitize(string s)
    {
        var chars = s.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray();
        var r = new string(chars);
        return string.IsNullOrEmpty(r) ? "X" : r;
    }
    private static string OneLine(string s) => s.Replace("\r", " ").Replace("\n", " ");
}
