using System.Text;

namespace ModForge;

public static partial class Generator
{
    // -------------------------------------------------------------------------------
    //  Reporting the dependency set (analysis is in Generator.Dependencies.cs).
    //
    //  INFORMATIONAL, never a warning — mod-sourced content is what the author asked for. (The one
    //  thing that IS an error is DRIFT against a declared requires[]: Generator.Requires.cs.)
    //  A spec that only touches vanilla must print NOTHING (this must not become background noise).
    // -------------------------------------------------------------------------------

    private const int ConsoleSources = 3;                        // per master, in the build summary
    private const int FileSources = 25;                          // per master, in the sidecar

    /// <summary>Build-summary lines. Empty when every master is vanilla.</summary>
    public static IReadOnlyList<string> DependencySummary(IReadOnlyList<MasterDependency> deps)
    {
        var external = deps.Where(d => !d.Vanilla).ToList();
        if (external.Count == 0) return Array.Empty<string>();

        var lines = new List<string>
        {
            $"{external.Count} non-vanilla master(s) — the plugin will NOT load for anyone missing them (Skyrim drops it silently):",
        };
        foreach (var d in external)
        {
            lines.Add($"  {d.Master}  ({d.Links} link(s)){(d.CreationClub ? "  [Creation Club — owned per account, not on every install]" : "")}");
            var why = Attribution(d);
            foreach (var s in why.Take(ConsoleSources)) lines.Add($"      ← {s}");
            if (why.Count > ConsoleSources) lines.Add($"      … +{why.Count - ConsoleSources} more");
        }
        return lines;
    }

    // The spec field when we know it (that is the line to delete); otherwise the records that dragged
    // the master in (a deep-copied record's own refs name no spec field at all).
    private static List<string> Attribution(MasterDependency d) =>
        d.SpecSources.Count > 0 ? d.SpecSources.ToList() : d.RecordSources.Select(r => $"record {r}").ToList();

    /// <summary>
    /// The <c>&lt;plugin&gt;.requires.txt</c> sidecar — a durable record of what this plugin needs
    /// (a build summary scrolls away, and nothing else anywhere says what an .esp depends on). This is
    /// the requirements list a player reads, so the spec's own <c>requires[]</c> metadata (reason /
    /// version / url, and the mods that have no plugin at all) is folded in when it is there.
    /// Null when there is nothing to report: no file should be written.
    /// </summary>
    public static string? RequiresFileText(
        string pluginName,
        IReadOnlyList<MasterDependency> deps,
        IReadOnlyList<RequirementSpec>? declared = null)
    {
        var external = deps.Where(d => !d.Vanilla).ToList();
        // Declared requirements with no plugin of their own (an SKSE DLL, a loose-file framework): they
        // can never show up as a master, so the sidecar is the ONLY place they are ever stated.
        var noPlugin = (declared ?? Array.Empty<RequirementSpec>())
            .Where(r => string.IsNullOrWhiteSpace(r.Plugin) && !string.IsNullOrWhiteSpace(r.Name)).ToList();
        if (external.Count == 0 && noPlugin.Count == 0) return null;

        var byPlugin = (declared ?? Array.Empty<RequirementSpec>())
            .Where(r => !string.IsNullOrWhiteSpace(r.Plugin))
            .GroupBy(r => r.Plugin.Trim(), StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

        var sb = new StringBuilder();
        sb.AppendLine($"# {pluginName} — install requirements (generated by `modforge build`)");
        sb.AppendLine("#");
        sb.AppendLine("# Every master listed below must be INSTALLED AND ENABLED, or Skyrim silently refuses to");
        sb.AppendLine("# load this plugin: no error, no log line, the records simply are not there in-game.");
        sb.AppendLine("# Under each master are the spec fields that name a form the plugin links from it.");
        sb.AppendLine("# To drop a dependency, remove ALL of that master's lines from the spec and rebuild.");
        sb.AppendLine("#");
        sb.AppendLine("# vanilla (in every install, no action needed): "
            + string.Join(", ", deps.Where(d => d.Vanilla).Select(d => d.Master).DefaultIfEmpty("none")));
        sb.AppendLine();
        sb.AppendLine($"requires {external.Count} non-vanilla master(s):");
        foreach (var d in external)
        {
            sb.AppendLine();
            sb.AppendLine($"{d.Master}  ({d.Links} link(s)){(d.CreationClub ? "  [Creation Club — owned per account, not on every install]" : "")}");
            var why = Attribution(d);
            // Skip a reason that only repeats the attribution below it (what --sync-requires auto-writes).
            if (byPlugin.TryGetValue(d.Master, out var r))
                AppendDeclared(sb, r, echoesAttribution: why.Any(s => s.StartsWith(r.Reason, StringComparison.Ordinal)));
            foreach (var s in why.Take(FileSources)) sb.AppendLine($"    {s}");
            if (why.Count > FileSources) sb.AppendLine($"    … +{why.Count - FileSources} more");
            if (d.SpecSources.Count > 0 && d.RecordSources.Count > 0)
                sb.AppendLine($"    records: {string.Join(", ", d.RecordSources.Take(FileSources))}");
        }

        if (noPlugin.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine($"also required, declared in the spec's requires[] — no plugin of its own, so it can never be a");
            sb.AppendLine($"master and ModForge cannot check it (an SKSE DLL, a loose-file framework):");
            foreach (var r in noPlugin)
            {
                sb.AppendLine();
                sb.AppendLine(r.Name);
                AppendDeclared(sb, r);
            }
        }
        return sb.ToString();
    }

    // The author's own words about a requirement. `version` is DOCUMENTATION ONLY and says so out loud:
    // a Skyrim plugin carries no mod version (TES4/HEDR's "version" is the file FORMAT version — 1.71 for
    // every SSE plugin alike; CNAM/SNAM are free text). Nothing can verify it, so nothing pretends to.
    private static void AppendDeclared(StringBuilder sb, RequirementSpec r, bool echoesAttribution = false)
    {
        if (r.Version.Length > 0) sb.AppendLine($"    version: {r.Version}   (as declared — NOT verified: a plugin carries no mod version)");
        if (r.Reason.Length > 0 && !echoesAttribution) sb.AppendLine($"    reason: {r.Reason}");
        if (r.Url.Length > 0) sb.AppendLine($"    get it: {r.Url}");
    }
}
