namespace ModForge;

public static partial class Generator
{
    // -------------------------------------------------------------------------------
    //  Quest fragment-script GENERATION (It. quest-stages).
    //
    //  Stages + log entries are pure RECORD data (built in Generator.Build). But two pieces
    //  of "quest LOGIC" can only run via Papyrus in Skyrim:
    //    * displaying / completing an OBJECTIVE when a stage is reached
    //      (SetObjectiveDisplayed / SetObjectiveCompleted), and
    //    * advancing a STAGE when a dialogue line is picked (GetOwningQuest().SetStage()).
    //  Vanilla does both with CK-generated fragment scripts (QF_<quest>_<formid> stage
    //  fragments + TIF_<formid> dialogue fragments). We can't drive the Creation Kit
    //  headless, so we GENERATE the equivalent Papyrus SOURCE for the author to compile
    //  (the `package` command writes it under Scripts/Source/). The quest base script is
    //  attached to the QUST record via the normal VMAD script mechanism; the per-stage
    //  Fragment_N hooks must be bound in the CK (the one step we can't do on Linux).
    //
    //  This generator is a pure function (string in / string out) so it's unit-testable
    //  with no Skyrim master / Wine dependency.
    // -------------------------------------------------------------------------------

    /// <summary>The Papyrus script Name attached to a quest that has stage→objective wiring or
    /// dialogue-set-stage logic. Empty if the quest needs no fragment script.</summary>
    public static string QuestFragmentScriptName(QuestSpec q) =>
        QuestNeedsFragmentScript(q) ? $"{Sanitize(q.EditorId)}_Stages" : "";

    /// <summary>True when a quest has objectives linked to stages (showStage/completeStage) or any stage
    /// binds an instance global (UpdateCurrentInstanceGlobal).</summary>
    public static bool QuestNeedsFragmentScript(QuestSpec q) =>
        q.Objectives.Any(o => o.ShowStage >= 0 || o.CompleteStage >= 0)
        || q.Stages.Any(s => s.InstanceGlobals.Count > 0);

    /// <summary>The Papyrus property name a stage fragment uses to reference an instance global — the
    /// sanitized global editorId (a vanilla ref keeps only its hex tail so it stays identifier-safe).</summary>
    internal static string InstanceGlobalProperty(string globalRef)
    {
        var s = Sanitize(globalRef);
        // A vanilla ref ("Skyrim_esm_0x12345" after sanitize) → "G_0x12345"-style safe stub.
        return char.IsLetter(s.FirstOrDefault()) ? s : "G_" + s;
    }

    /// <summary>The Papyrus source for a quest's stage-fragment script. One Fragment per stage that
    /// displays/completes the objectives linked to it. Function names follow the CK convention
    /// (<c>Fragment_Stage_XXXX_Item00000</c>) so the engine calls them automatically when
    /// <c>SetStage()</c> fires — no CK binding step needed once the .pex is compiled and the
    /// VMAD is attached by <c>package</c>.</summary>
    public static string GenerateQuestFragmentSource(QuestSpec q)
    {
        if (!QuestNeedsFragmentScript(q)) return "";
        var name = QuestFragmentScriptName(q);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends Quest");
        sb.AppendLine("; AUTO-GENERATED by ModForge — quest stage → objective wiring + instance globals.");
        sb.AppendLine("; `package` compiles this and attaches the QuestAdapter VMAD automatically;");
        sb.AppendLine("; no Creation Kit binding step is needed.");
        sb.AppendLine();

        // GlobalVariable properties for every distinct instance global referenced by any stage. The
        // VMAD (WireQuestStages) binds each to its GLOB FormKey; the fragment body uses them by name.
        var instGlobals = q.Stages
            .SelectMany(s => s.InstanceGlobals)
            .Select(g => g.Global).Where(g => !string.IsNullOrWhiteSpace(g))
            .Distinct(StringComparer.OrdinalIgnoreCase).ToList();
        foreach (var g in instGlobals)
            sb.AppendLine($"GlobalVariable Property {InstanceGlobalProperty(g)} Auto");
        if (instGlobals.Count > 0) sb.AppendLine();

        // Every stage that shows/completes an objective OR binds an instance global, ascending.
        var objStages = q.Objectives.SelectMany(o => new[] { o.ShowStage, o.CompleteStage }).Where(s => s >= 0);
        var instStages = q.Stages.Where(s => s.InstanceGlobals.Count > 0).Select(s => (int)s.Index);
        var stageNums = objStages.Concat(instStages).Distinct().OrderBy(s => s);

        foreach (var stage in stageNums)
        {
            // CK-standard name: engine calls Fragment_Stage_XXXX_Item00000 on the script when
            // SetStage(XXXX) fires (first log entry = Item00000). No manual binding required.
            sb.AppendLine($"Function Fragment_Stage_{stage:D4}_Item00000()");
            foreach (var o in q.Objectives.Where(o => o.ShowStage == stage))
                sb.AppendLine($"    SetObjectiveDisplayed({o.Index})   ; show: {OneLine(o.Text)}");
            foreach (var o in q.Objectives.Where(o => o.CompleteStage == stage))
                sb.AppendLine($"    SetObjectiveCompleted({o.Index})   ; complete: {OneLine(o.Text)}");
            // Instance globals: optionally seed the value, then bind it to this quest instance so
            // objective text "<Global=X>" reads per-instance (gather/count radiant quests).
            foreach (var ig in q.Stages.Where(s => s.Index == stage).SelectMany(s => s.InstanceGlobals))
            {
                var p = InstanceGlobalProperty(ig.Global);
                if (ig.RandomMin is int lo && ig.RandomMax is int hi)
                    sb.AppendLine($"    {p}.SetValue(Utility.RandomInt({lo}, {hi}))");
                else if (ig.Value is float v)
                    sb.AppendLine($"    {p}.SetValue({OneLine(v.ToString(System.Globalization.CultureInfo.InvariantCulture))})");
                sb.AppendLine($"    UpdateCurrentInstanceGlobal({p})");
            }
            sb.AppendLine("EndFunction");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    /// <summary>Property name on a generated TIF script that holds the owning quest reference.</summary>
    internal const string TifQuestPropertyName = "OwningQuest";

    /// <summary>Scriptname of the reusable presence-gated Scene controller (extends Quest), attached to a
    /// host quest when a scene declares autoStart. One prebuilt .pex (embedded in the CLI) serves every
    /// generated mod; Package ships it whenever a scene uses autoStart.</summary>
    internal const string SceneBanterController = "MFSceneBanterController";

    /// <summary>Scriptname of the reusable primary-identity controller (extends Quest). Maintains the
    /// MF_PrimaryIdentity global; one prebuilt .pex (embedded in the CLI) serves every generated mod.</summary>
    internal const string IdentityController = "MFIdentityController";

    /// <summary>The auto-built global holding the player's CURRENT primary identity code (0 = none). Read
    /// by primaryIdentity greeting CTDA; written by the controller.</summary>
    internal const string IdentityPrimaryGlobal = "MF_PrimaryIdentity";

    /// <summary>The auto-built global holding the player's MANUAL override code (0 = auto). Written by a
    /// dialogue option (setPrimaryIdentity); read by the controller.</summary>
    internal const string IdentityOverrideGlobal = "MF_IdentityOverride";

    /// <summary>The stable per-identity numeric code used by the controller / greeting CTDA / override
    /// fragment: 1-based index into spec.Identities. 0 for "auto"/empty (no/clear override); -1 if unknown.</summary>
    public static int IdentityCode(ModSpec spec, string id)
    {
        if (string.IsNullOrWhiteSpace(id) || string.Equals(id, "auto", StringComparison.OrdinalIgnoreCase)) return 0;
        for (int i = 0; i < spec.Identities.Count; i++)
            if (string.Equals(spec.Identities[i].Id, id, StringComparison.OrdinalIgnoreCase)) return i + 1;
        return -1;
    }

    /// <summary>The Papyrus source for a dialogue line that advances a stage and/or sets the primary-identity
    /// override when picked (the TIF dialogue-fragment equivalent). SetStage uses an explicit Quest property
    /// rather than GetOwningQuest() — GetOwningQuest() can return None at runtime for StartGameEnabled quests,
    /// silently skipping SetStage. Properties are bound in the INFO VMAD by <c>package</c>. <paramref
    /// name="overrideCode"/> ≥ 0 emits the override SetValue (0 = clear/auto); -1 = no override line.</summary>
    /// <summary>Property name on a generated TIF script that holds the reward item/gold form.</summary>
    internal const string TifRewardPropertyName = "RewardItem";
    /// <summary>Property name on a generated TIF script that holds the mutable reputation/counter global.</summary>
    internal const string TifSetGlobalPropertyName = "TargetGlobal";

    public static string GenerateDialogueFragmentSource(DialogueSpec d, int overrideCode = -1)
    {
        bool setsStage = d.SetStage >= 0;
        bool setsOverride = overrideCode >= 0;
        bool opensBarter = d.OpenBarter;
        bool setsGlobal = d.SetGlobal is { } sg && !string.IsNullOrWhiteSpace(sg.Global) && (sg.Value.HasValue || sg.Delta.HasValue);
        bool rewards = !string.IsNullOrWhiteSpace(d.RewardItem);
        bool reevals = d.EvaluateSpeakerPackages;
        if (!setsStage && !setsOverride && !opensBarter && !setsGlobal && !rewards && !reevals) return "";
        var name = DialogueFragmentScriptName(d);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends TopicInfo Hidden");
        sb.AppendLine("; AUTO-GENERATED by ModForge — dialogue line result (setStage / identity override / global / barter / reward / re-eval).");
        sb.AppendLine("; Object properties are bound to their FormKeys in the ESP VMAD by `package`.");
        sb.AppendLine();
        if (setsStage) sb.AppendLine($"Quest Property {TifQuestPropertyName} Auto");
        if (setsOverride) sb.AppendLine($"GlobalVariable Property {IdentityOverrideGlobal} Auto");
        if (setsGlobal) sb.AppendLine($"GlobalVariable Property {TifSetGlobalPropertyName} Auto");
        if (rewards) sb.AppendLine($"Form Property {TifRewardPropertyName} Auto");
        sb.AppendLine();
        sb.AppendLine("Function Fragment_0(ObjectReference akSpeakerRef)");
        if (setsStage) sb.AppendLine($"    {TifQuestPropertyName}.SetStage({d.SetStage})");
        if (setsOverride) sb.AppendLine($"    {IdentityOverrideGlobal}.SetValue({overrideCode})");
        if (setsGlobal)
        {
            if (d.SetGlobal!.Value.HasValue)
                sb.AppendLine($"    {TifSetGlobalPropertyName}.SetValue({PapyrusFloat(d.SetGlobal.Value.Value)})");
            if (d.SetGlobal.Delta.HasValue)
                sb.AppendLine($"    {TifSetGlobalPropertyName}.Mod({PapyrusFloat(d.SetGlobal.Delta.Value)})");
        }
        if (rewards) sb.AppendLine($"    Game.GetPlayer().AddItem({TifRewardPropertyName}, {(d.RewardCount < 1 ? 1 : d.RewardCount)})");
        if (opensBarter || reevals)
        {
            sb.AppendLine("    Actor __spk = akSpeakerRef as Actor");
            sb.AppendLine("    If __spk");
            // Vanilla natives — ShowBarterMenu() opens trade with a vendor speaker; EvaluatePackage()
            // re-runs the speaker's AI packages so a stage-gated follow/escort package activates now.
            if (opensBarter) sb.AppendLine("        __spk.ShowBarterMenu()");
            if (reevals)     sb.AppendLine("        __spk.EvaluatePackage()");
            sb.AppendLine("    EndIf");
        }
        sb.AppendLine("EndFunction");
        return sb.ToString();
    }

    public static string DialogueFragmentScriptName(DialogueSpec d) =>
        (d.SetStage >= 0 || !string.IsNullOrWhiteSpace(d.SetPrimaryIdentity) || d.OpenBarter
         || (d.SetGlobal is { } sg && !string.IsNullOrWhiteSpace(sg.Global)) || !string.IsNullOrWhiteSpace(d.RewardItem)
         || d.EvaluateSpeakerPackages) ? $"TIF_{Sanitize(d.EditorId)}" : "";

    private static string Sanitize(string s)
    {
        var chars = s.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray();
        var r = new string(chars);
        return string.IsNullOrEmpty(r) ? "X" : r;
    }
    private static string OneLine(string s) => s.Replace("\r", " ").Replace("\n", " ");
    private static string PapyrusFloat(float v) => v.ToString("0.########", System.Globalization.CultureInfo.InvariantCulture);
}
