namespace ModForge;

public static partial class Generator
{
    // -------------------------------------------------------------------------------
    //  Quest fragment-script GENERATION (It. quest-stages).
    //
    //  Stages + log entries are pure RECORD data (built in Generator.Build). But two pieces
    //  of "quest LOGIC" can only run via Papyrus in Skyrim:
    //    * displaying / completing an OBJECTIVE when a stage is reached
    //      (SetObjectiveDisplayed / SetObjectiveCompleted), and
    //    * advancing a STAGE when a dialogue line is picked (GetOwningQuest().SetStage()).
    //  Vanilla does both with CK-generated fragment scripts (QF_<quest>_<formid> stage
    //  fragments + TIF_<formid> dialogue fragments). We can't drive the Creation Kit
    //  headless, so we GENERATE the equivalent Papyrus SOURCE for the author to compile
    //  (the `package` command writes it under Scripts/Source/). The quest base script is
    //  attached to the QUST record via the normal VMAD script mechanism; the per-stage
    //  Fragment_N hooks must be bound in the CK (the one step we can't do on Linux).
    //
    //  This generator is a pure function (string in / string out) so it's unit-testable
    //  with no Skyrim master / Wine dependency.
    // -------------------------------------------------------------------------------

    /// <summary>The Papyrus script Name attached to a quest that has stage→objective wiring or
    /// dialogue-set-stage logic. Empty if the quest needs no fragment script.</summary>
    public static string QuestFragmentScriptName(QuestSpec q) =>
        QuestNeedsFragmentScript(q) ? $"{Sanitize(q.EditorId)}_Stages" : "";

    /// <summary>True when a quest has objectives linked to stages (showStage/completeStage).</summary>
    public static bool QuestNeedsFragmentScript(QuestSpec q) =>
        q.Objectives.Any(o => o.ShowStage >= 0 || o.CompleteStage >= 0);

    /// <summary>The Papyrus source for a quest's stage-fragment script. One Fragment helper per stage
    /// that displays/completes the objectives linked to it. Returns "" if the quest needs no script.</summary>
    public static string GenerateQuestFragmentSource(QuestSpec q)
    {
        if (!QuestNeedsFragmentScript(q)) return "";
        var name = QuestFragmentScriptName(q);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends Quest");
        sb.AppendLine("; AUTO-GENERATED by ModForge — quest stage → objective wiring.");
        sb.AppendLine("; Compile this, then in the Creation Kit bind each ApplyStage* call from the");
        sb.AppendLine("; matching QUST stage's fragment (Papyrus Fragment tab) — the engine fires a");
        sb.AppendLine("; stage fragment when SetStage() reaches that stage. Each fragment body should");
        sb.AppendLine($"; be a single line: ({name} as Quest).ApplyStage_<N>()  (or call SetObjective* directly).");
        sb.AppendLine();

        // Stages that show or complete an objective, in ascending order.
        var stageNums = q.Objectives
            .SelectMany(o => new[] { o.ShowStage, o.CompleteStage })
            .Where(s => s >= 0).Distinct().OrderBy(s => s);

        foreach (var stage in stageNums)
        {
            sb.AppendLine($"Function ApplyStage_{stage}()");
            foreach (var o in q.Objectives.Where(o => o.ShowStage == stage))
                sb.AppendLine($"    SetObjectiveDisplayed({o.Index})   ; show: {OneLine(o.Text)}");
            foreach (var o in q.Objectives.Where(o => o.CompleteStage == stage))
                sb.AppendLine($"    SetObjectiveCompleted({o.Index})   ; complete: {OneLine(o.Text)}");
            sb.AppendLine("EndFunction");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    /// <summary>The Papyrus source for a dialogue line that advances a stage when picked (the TIF
    /// dialogue-fragment equivalent). Returns "" if the line sets no stage.</summary>
    public static string GenerateDialogueFragmentSource(DialogueSpec d)
    {
        if (d.SetStage < 0) return "";
        var name = DialogueFragmentScriptName(d);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends TopicInfo Hidden");
        sb.AppendLine("; AUTO-GENERATED by ModForge — dialogue line → SetStage.");
        sb.AppendLine("; In the Creation Kit, paste the Fragment_0 body into this INFO's 'End' result");
        sb.AppendLine("; script box, OR bind this script as the topic-info fragment.");
        sb.AppendLine();
        sb.AppendLine("Function Fragment_0(ObjectReference akSpeakerRef)");
        sb.AppendLine($"    GetOwningQuest().SetStage({d.SetStage})   ; advance '{Sanitize(d.QuestEditorId)}' to stage {d.SetStage}");
        sb.AppendLine("EndFunction");
        return sb.ToString();
    }

    public static string DialogueFragmentScriptName(DialogueSpec d) =>
        d.SetStage >= 0 ? $"TIF_{Sanitize(d.EditorId)}" : "";

    private static string Sanitize(string s)
    {
        var chars = s.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray();
        var r = new string(chars);
        return string.IsNullOrEmpty(r) ? "X" : r;
    }
    private static string OneLine(string s) => s.Replace("\r", " ").Replace("\n", " ");
}
