namespace ModForge;

public static partial class Generator
{
    // -------------------------------------------------------------------------------
    //  Perk fragment-script GENERATION (Immersive-Interactions-style activate choices).
    //
    //  A perk `addActivateChoice` effect with a `fragmentBody` runs Papyrus when its "[E] <label>"
    //  choice is picked. Vanilla stores this as a PerkAdapter VMAD whose PerkScriptFragments bind a
    //  Fragment_<index> function (on a script extending Perk) to the entry point by FragmentIndex.
    //  We can't drive the CK headless, so we GENERATE the equivalent .psc for `package` to compile;
    //  Build() attaches the PerkAdapter VMAD only when the compiled .pex is present (same gating as
    //  quest/dialogue/scene fragments — a VMAD pointing at an absent .pex errors at load).
    //
    //  ⚠ The Activate-perk fragment SIGNATURE (akTargetRef + akActor) and the PerkAdapter byte fields
    //  (Version/ObjectFormat, ExtraBindDataVersion, IndexedScriptFragment Unknown fields) are set to
    //  best-justified values; they need a main-machine xEdit byte-compare vs a real Immersive
    //  Interactions perk (see WAIT_USER). Pure function (string in / string out), unit-testable.
    // -------------------------------------------------------------------------------

    /// <summary>The fragment-bearing activate choices of a perk, in declaration order (their position
    /// here IS their FragmentIndex). Empty when the perk needs no fragment script.</summary>
    internal static List<PerkEffectSpec> PerkFragmentChoices(PerkSpec p) =>
        p.Effects.Where(e => string.Equals(e.Kind, "addActivateChoice", StringComparison.OrdinalIgnoreCase)
                             && !string.IsNullOrWhiteSpace(e.FragmentBody)).ToList();

    public static bool PerkNeedsFragmentScript(PerkSpec p) => PerkFragmentChoices(p).Count > 0;

    public static string PerkFragmentScriptName(PerkSpec p) =>
        PerkNeedsFragmentScript(p) ? $"{Sanitize(p.EditorId)}_Frags" : "";

    /// <summary>Papyrus source for a perk's activate-choice fragments — one Fragment_&lt;index&gt; per
    /// fragment-bearing addActivateChoice, in declaration order. akTargetRef = the activated object,
    /// akActor = the activator.</summary>
    public static string GeneratePerkFragmentSource(PerkSpec p)
    {
        var choices = PerkFragmentChoices(p);
        if (choices.Count == 0) return "";
        var name = PerkFragmentScriptName(p);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Scriptname {name} extends Perk");
        sb.AppendLine("; AUTO-GENERATED by ModForge — perk activate-choice fragments.");
        sb.AppendLine("; `package` compiles this and attaches the PerkAdapter VMAD automatically.");
        sb.AppendLine();
        for (int i = 0; i < choices.Count; i++)
        {
            sb.AppendLine($"Function Fragment_{i}(ObjectReference akTargetRef, Actor akActor)");
            if (!string.IsNullOrWhiteSpace(choices[i].ButtonLabel))
                sb.AppendLine($"    ; [E] {OneLine(choices[i].ButtonLabel)}");
            foreach (var line in SplitBody(choices[i].FragmentBody))
                sb.AppendLine("    " + line);
            sb.AppendLine("EndFunction");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    // Split a user fragment body into trimmed non-empty lines (accepts \n or literal \\n separators).
    private static IEnumerable<string> SplitBody(string body) =>
        body.Replace("\\n", "\n").Split('\n').Select(l => l.TrimEnd()).Where(l => l.Trim().Length > 0);
}
